apiVersion: apps/v1
kind: Deployment
metadata:
  name: bananashop-net
  labels:
    app: bananashop-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bananashop-net
  template:
    metadata:
      labels:
        app: bananashop-net
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5001"
    spec:
      containers:
      - name: bananashop-net
        image: angeloxx/bananashopnet:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: bananashop
spec:
  sessionAffinity: None
  selector:
    app: bananashop-net
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30011
  type: NodePort
---
  apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    name: bananashop-net
  spec:
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: bananashop-net
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: Pods
      pods:
        metricName: win_banana_metrics_perminute
        targetAverageValue: 30